[pytest]
# Минимальная конфигурация
asyncio_mode = auto

# Добавляем пути к модулям
pythonpath = .

# Маркеры
markers =
    asyncio: асинхронные тесты

# Фильтруем предупреждения
filterwarnings =
    ignore::DeprecationWarning